// components/airportLogos.js

const airportLogos = {
  ATL: require('../assets/logos/ATL.png'),
  AUS: require('../assets/logos/AUS.png'),
  BNA: require('../assets/logos/BNA.png'),
  BOS: require('../assets/logos/BOS.png'),
  BWI: require('../assets/logos/BWI.png'),
  CLE: require('../assets/logos/CLE.png'),
  CLT: require('../assets/logos/CLT.png'),
  CMH: require('../assets/logos/CMH.png'),
  CVG: require('../assets/logos/CVG.png'),
  DEN: require('../assets/logos/DEN.png'),
  DFW: require('../assets/logos/DFW.png'),
  DTW: require('../assets/logos/DTW.png'),
  EWR: require('../assets/logos/EWR.png'),
  FLL: require('../assets/logos/FLL.png'),
  HNL: require('../assets/logos/HNL.png'),
  IAD: require('../assets/logos/IAD.png'),
  IAH: require('../assets/logos/IAH.png'),
  IND: require('../assets/logos/IND.png'),
  JAX: require('../assets/logos/JAX.png'),
  JFK: require('../assets/logos/JFK.png'),
  LAS: require('../assets/logos/LAS.png'),
  LAX: require('../assets/logos/LAX.png'),
  LGA: require('../assets/logos/LGA.png'),
  MCI: require('../assets/logos/MCI.png'),
  MCO: require('../assets/logos/MCO.png'),
  MDW: require('../assets/logos/MDW.png'),
  MIA: require('../assets/logos/MIA.png'),
  MSP: require('../assets/logos/MSP.png'),
  MSY: require('../assets/logos/MSY.png'),
  OGG: require('../assets/logos/OGG.png'),
  ORD: require('../assets/logos/ORD.png'),
  PBI: require('../assets/logos/PBI.png'),
  PDX: require('../assets/logos/PDX.png'),
  PHL: require('../assets/logos/PHL.png'),
  PHX: require('../assets/logos/PHX.png'),
  PIT: require('../assets/logos/PIT.png'),
  RDU: require('../assets/logos/RDU.png'),
  RSW: require('../assets/logos/RSW.png'),
  SAN: require('../assets/logos/SAN.png'),
  SEA: require('../assets/logos/SEA.png'),
  SFO: require('../assets/logos/SFO.png'),
  SJC: require('../assets/logos/SJC.png'),
  SJU: require('../assets/logos/SJU.png'),
  SLC: require('../assets/logos/SLC.png'),
  SMF: require('../assets/logos/SMF.png'),
  SNA: require('../assets/logos/SNA.png'),
  STL: require('../assets/logos/STL.png'),
  TPA: require('../assets/logos/TPA.png'),
  default: require('../assets/logos/default_airport.png'),
};

export const getAirportLogo = (code) =>
  airportLogos[code?.toUpperCase()] || airportLogos.default;
